print("Hello World")
print("Hello Again")
print("I like typing this.")
print("This is fun")
print('Yay!printing.')
print("i'd much rather you 'not'.")
print('I "said" do not touch this.')
print("a line more")
